if (!variable_global_exists("user_logged_in") || !global.user_logged_in)
{
    show_message_async("Debes iniciar sesión para subir texturas");
    instance_destroy();
    exit;
}

instance_deactivate_object(obj_aventura);
instance_deactivate_object(obj_carlosXDjav);
instance_deactivate_object(obj_otrosmodos);
instance_deactivate_object(obj_opciones);
instance_deactivate_object(obj_Hellomario_version);
instance_deactivate_object(obj_bganimator);
instance_deactivate_object(obj_cursor_menu);
instance_deactivate_object(obj_cursor_menu_manager);
instance_deactivate_object(obj_text_in_screen_Custom);
instance_deactivate_object(obj_text_Special);
instance_deactivate_object(obj_menu_eventos);
depth = -1000;
estado = 0;
texture_folder_path = "";
texture_name = "";
texture_description = "";
texture_image_path = "";
simplepack_path = "";
simplepack_created = false;
r2_file_name = "";
r2_thumb_name = "";
cold_storage_id = "";
request_upload_texture = -1;
request_upload_thumb = -1;
request_create_db = -1;
request_catbox = -1;
catbox_file_id = "";
esperando_catbox_db = false;
upload_step = 0;
loading = false;
mensaje = "";
mensaje_color = 16777215;
tags_disponibles = ds_list_create();
ds_list_add(tags_disponibles, "SMB1");
ds_list_add(tags_disponibles, "SMB2");
ds_list_add(tags_disponibles, "SMB3");
ds_list_add(tags_disponibles, "SMW");
ds_list_add(tags_disponibles, "NSMB");
ds_list_add(tags_disponibles, "SMM");
ds_list_add(tags_disponibles, "WONDER");
ds_list_add(tags_disponibles, "HD");
tags_seleccionados = ds_list_create();
packing_active = false;
pack_buffer = -1;
pack_files = ds_list_create();
pack_index = 0;
pack_total = 0;
pack_base_dir = "";
pack_progress = 0;
centro_x = room_width / 2;
campo_w = 400;
campo_h = 40;
campo_activo = 0;
campo_activo_prev = -1;
color_fondo = make_colour_rgb(20, 12, 40);
color_campo = make_colour_rgb(50, 30, 90);
color_campo_activo = make_colour_rgb(70, 50, 120);
color_boton = make_colour_rgb(180, 80, 220);
color_boton_hover = make_colour_rgb(220, 120, 255);
preview_sprite = -1;
depth = -5000;
estado = -1;
item_type = "texture";
tags_customs = ds_list_create();
ds_list_add(tags_customs, "Enemy", "Mini Boss", "Boss", "Manager", "Utility", "SFX", "NPC", "Block", "Item");
android_picking = false;
android_file_list = -1;
android_scroll = 0;
