color_fondo = make_colour_rgb(20, 10, 40);
color_panel = make_colour_rgb(40, 25, 80);
color_panel_light = make_colour_rgb(60, 40, 100);
color_accent = make_colour_rgb(255, 215, 0);
color_btn = make_colour_rgb(80, 50, 140);
color_btn_hover = make_colour_rgb(100, 70, 160);
centro_x = room_width / 2;
loading = 1;
profile_image_url = "";
profile_image_sprite = -1;
profile_image_loading = 0;
profile_image_request = -1;
profile_image_loaded = 0;
image_retry_count = 0;
image_max_retries = 3;
bio = "";
total_likes = 0;
total_downloads = 0;
levels_count = 0;
member_since = "";
my_levels = ds_list_create();
my_levels_loaded = 0;
my_badges = ds_list_create();
my_badges_loaded = 0;
all_badges = ds_list_create();
all_badges_loaded = 0;
badge_hover_index = -1;
badge_hover_timer = 0;
badge_hover_threshold = game_get_speed(gamespeed_fps) * 0.4;
show_badge_tooltip = 0;
tooltip_badge_index = -1;
show_add_badge_menu = 0;
badges_retry_count = 0;
badges_max_retries = 3;
request_all_badges = -1;
request_award_badge = -1;
request_remove_badge = -1;
request_profile = -1;
request_levels = -1;
request_badges = -1;
request_save_profile = -1;
request_upload_image = -1;
request_stats = -1;
request_xp_stats = -1;
stats_loaded = 0;
user_total_xp = 0;
user_current_level = 1;
user_xp_loaded = 0;
discord_linked = 0;
discord_username = "";
discord_id = "";
discord_link_code = "";
show_discord_popup = 0;
request_discord_check = -1;
request_discord_link = -1;
discord_hover_timer = 0;
show_discord_tooltip = 0;
request_profile = scr_load_my_profile();
request_levels = scr_load_my_levels();
request_badges = scr_load_my_badges();
request_stats = scr_load_my_stats();
request_xp_stats = scr_load_my_xp_stats();
request_discord_check = scr_check_discord_linked();
instance_deactivate_object(obj_aventura);
instance_deactivate_object(obj_carlosXDjav);
instance_deactivate_object(obj_otrosmodos);
instance_deactivate_object(obj_opciones);
instance_deactivate_object(obj_Hellomario_version);
instance_deactivate_object(obj_bganimator);
instance_deactivate_object(obj_cursor_menu);
instance_deactivate_object(obj_cursor_menu_manager);
instance_deactivate_object(obj_text_in_screen_Custom);
instance_deactivate_object(obj_text_Special);
instance_deactivate_object(obj_menu_eventos);
depth = -3333;
android_picking = false;
android_file_list = -1;
android_scroll = 0;

perfil_sc = max(1, floor(min(room_width / 384, room_height / 216)));
perfil_ox = floor((room_width - 384 * perfil_sc) / 2);
perfil_oy = floor((room_height - 216 * perfil_sc) / 2);

hover_volver_a = 0;
hover_cerrar_a = 0;
hover_discord_a = 0;

// rects de las insignias calculados en el step y leidos en el draw
insig_rects = [];
insig_add_x = 0;
insig_add_y = 0;
niveles_y = 190;

// secciones colapsables del perfil, como las categorias del menu de
// personalizar: hover que las aclara y click que pliega el contenido
sec_insig_col = false;
sec_niveles_col = false;
hover_sec_insig_a = 0;
hover_sec_niveles_a = 0;
